name: Release (backend)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build JAR
        run: |
          chmod +x mvnw
          ./mvnw -B -q -DskipTests package
      - name: Empacotar artefato
        run: |
          mkdir -p artifacts
          cp target/*.jar artifacts/
      - name: Criar GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
          generate_release_notes: true
